export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'

export const REQUEST_ROOBOTS_PENDING = 'REQUEST_ROOBOTS_PENDING';
export const REQUEST_ROOBOTS_SUCCESS = 'REQUEST_ROOBOTS_SUCCESS';
export const REQUEST_ROOBOTS_FAILED = 'REQUEST_ROOBOTS_FAILED';